-- ============================================================================
-- SUPABASE PRODUCT INTELLIGENCE SCHEMA — FINALIZED DRAFT
-- ============================================================================
-- Purpose: Persist deterministic enrichment fields and RAG-ready product
--          documents for the ProductIntel AI platform (v1: smartphones,
--          foldable smartphones).
--
-- Status:  FINALIZED DRAFT — Ready for manual execution in Supabase SQL
--          editor after confirming:
--          1. pgvector extension is available in your Supabase project
--             (check: SELECT * FROM pg_available_extensions WHERE name = 'vector')
--          2. Supabase write path is implemented in app code (Phase 18-D+)
--          3. Fallback product ID handling is acceptable (product_id NULL
--             for rows without a corresponding products.id)
--
-- How to apply:
--   1. Open Supabase Dashboard → SQL Editor
--   2. Uncomment line 26 (CREATE EXTENSION vector) if pgvector not enabled
--   3. Uncomment the embedding column at line 155 if storing embeddings
--   4. Uncomment the vector index at line 200 if querying embeddings
--   5. Run this entire file
--   6. Verify: SELECT COUNT(*) FROM product_intelligence; -- expects 0
--
-- Source:  Phase 18-B of the ProductIntel project
--          2026-05-24
-- ============================================================================

-- ============================================================================
-- EXTENSION: pgvector
-- Required for the embedding VECTOR column and similarity search.
-- Supabase projects have pgvector available by default; uncomment only if
-- it is not already enabled.
-- Check with: SELECT * FROM pg_extension WHERE extname = 'vector';
-- ============================================================================
-- CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA extensions;

-- ============================================================================
-- TABLE: product_intelligence
-- Stores deterministic enrichment fields generated by
-- src/lib/product-enrichment.ts (buildProductEnrichmentProfile).
-- ============================================================================
CREATE TABLE IF NOT EXISTS product_intelligence (
  -- Primary key
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Foreign key to products table.
  -- product_id is NULLABLE because fallback products use non-UUID string IDs
  -- (e.g., "1", "2", … "7") and may not have a corresponding row in the
  -- Supabase products table. For real Supabase products, this should be a
  -- FK to products.id after migration.
  product_id UUID,

  -- Slug for direct lookup (unique, indexed below).
  slug TEXT NOT NULL,

  -- Enrichment fields (generated from Product scores, specs, pros/cons)
  product_summary TEXT,
  buying_verdict TEXT,
  best_for TEXT[],
  not_best_for TEXT[],
  strengths TEXT[],
  weaknesses TEXT[],

  -- Categorical tags for filtering and discovery
  ai_tags TEXT[],

  -- Use-case labels
  use_cases TEXT[],

  -- Buyer persona description
  buyer_persona TEXT,

  -- Data quality metrics
  data_quality_score NUMERIC,
  data_quality_level TEXT,

  -- Provenance
  source_version TEXT   DEFAULT '18-b',  -- tracks which enrichment logic version
  generated_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at   TIMESTAMPTZ DEFAULT NOW(),

  -- Uniqueness constraint (one intelligence row per slug)
  CONSTRAINT uq_product_intelligence_slug UNIQUE (slug)
);

-- Comments on the table and key columns
COMMENT ON TABLE product_intelligence IS
  'Deterministic enrichment fields per product slug. Generated by src/lib/product-enrichment.ts. Not source data — can be regenerated at any time.';
COMMENT ON COLUMN product_intelligence.product_id IS
  'Nullable: fallback products (IDs "1"–"7") have no Supabase row. Real products will FK to products.id.';
COMMENT ON COLUMN product_intelligence.product_summary IS
  'Concise brand + name + category + score tier summary.';
COMMENT ON COLUMN product_intelligence.buying_verdict IS
  'One-sentence buying recommendation based on overall score tier.';
COMMENT ON COLUMN product_intelligence.best_for IS
  'Use-case labels for scores >= 90 (e.g., "Mobile gamers", "Photography enthusiasts").';
COMMENT ON COLUMN product_intelligence.not_best_for IS
  'Use-case labels for scores < 80 or price constraints.';
COMMENT ON COLUMN product_intelligence.strengths IS
  'Top 3 score dimensions + first 2 pros.';
COMMENT ON COLUMN product_intelligence.weaknesses IS
  'Bottom 2 score dimensions + first 3 cons + data quality note.';
COMMENT ON COLUMN product_intelligence.ai_tags IS
  'Deterministic tags: category, brand, tier, dimensions, price-range. Used for filtering.';
COMMENT ON COLUMN product_intelligence.use_cases IS
  'Human-readable use case sentences for high-scoring dimensions.';
COMMENT ON COLUMN product_intelligence.buyer_persona IS
  'Descriptive buyer persona based on price segment, priorities, and form factor.';
COMMENT ON COLUMN product_intelligence.source_version IS
  'Tracks which phase/version of enrichment logic generated this row (e.g., "17-c", "17-f").';
COMMENT ON COLUMN product_intelligence.generated_at IS
  'When this enrichment row was first generated.';
COMMENT ON COLUMN product_intelligence.updated_at IS
  'When this enrichment row was last regenerated.';

-- Indexes for product_intelligence
CREATE INDEX IF NOT EXISTS idx_product_intelligence_slug
  ON product_intelligence (slug);

CREATE INDEX IF NOT EXISTS idx_product_intelligence_product_id
  ON product_intelligence (product_id);

-- GIN index for array containment queries on ai_tags
-- Example: SELECT * FROM product_intelligence WHERE ai_tags @> ARRAY['gaming', 'premium'];
CREATE INDEX IF NOT EXISTS idx_product_intelligence_ai_tags
  ON product_intelligence USING GIN (ai_tags);

-- ============================================================================
-- TABLE: product_documents
-- Stores RAG-ready product document text and future embeddings.
-- One row per chunk per product.
-- ============================================================================
CREATE TABLE IF NOT EXISTS product_documents (
  -- Primary key
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Foreign key to products table (nullable — same reasoning as above).
  product_id UUID,

  -- Slug for lookup and correlation with product_intelligence.
  slug TEXT NOT NULL,

  -- Full product document text (from src/lib/product-document.ts).
  -- This is the source text from which chunks are derived.
  document_text TEXT NOT NULL,

  -- Chunk position within the document (0-based).
  chunk_index INTEGER DEFAULT 0,

  -- Individual chunk text for RAG retrieval.
  chunk_text TEXT,

  -- Metadata for filtering and provenance.
  -- Includes: name, brand, category, price, scores, source_version
  metadata JSONB,

  -- Embedding vector for semantic search.
  -- Requires pgvector extension (uncomment at top of file).
  -- Dimension 1536 matches OpenAI text-embedding-3-small.
  -- Uncomment when pgvector is approved and provider is decided.
  -- embedding VECTOR(1536),

  -- Provenance
  source_version TEXT DEFAULT '18-b',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),

  -- Uniqueness: one specific chunk per product
  CONSTRAINT uq_product_documents_slug_chunk UNIQUE (slug, chunk_index)
);

-- Comments on the table and key columns
COMMENT ON TABLE product_documents IS
  'RAG-ready product document chunks with optional embeddings. Generated by src/lib/product-document.ts and src/lib/enrichment-batch.ts.';
COMMENT ON COLUMN product_documents.product_id IS
  'Nullable: fallback products have no Supabase row. Real products will FK to products.id.';
COMMENT ON COLUMN product_documents.document_text IS
  'Full product document text: name, brand, category, description, price, scores, specs, pros, cons.';
COMMENT ON COLUMN product_documents.chunk_index IS
  'Position of this chunk within the full document (0 = first chunk).';
COMMENT ON COLUMN product_documents.chunk_text IS
  'Individual text chunk for vector search. For single-chunk documents, equals document_text.';
COMMENT ON COLUMN product_documents.metadata IS
  'JSON object containing: name, brand, category, price, overall_score, camera_score, battery_score, gaming_score, display_score, value_score, source_version.';
-- COMMENT ON COLUMN product_documents.embedding IS
--   'Vector embedding (1536d) for cosine similarity search. Generated by OpenAI text-embedding-3-small. Requires pgvector extension.';
COMMENT ON COLUMN product_documents.source_version IS
  'Tracks which phase/version of document generation logic built this row.';

-- Indexes for product_documents
CREATE INDEX IF NOT EXISTS idx_product_documents_slug
  ON product_documents (slug);

CREATE INDEX IF NOT EXISTS idx_product_documents_product_id
  ON product_documents (product_id);

-- GIN index for JSONB metadata queries
-- Example: SELECT * FROM product_documents WHERE metadata @> '{"brand": "Samsung"}';
CREATE INDEX IF NOT EXISTS idx_product_documents_metadata
  ON product_documents USING GIN (metadata);

-- Vector index for embedding similarity search (future).
-- Requires pgvector extension and populated embedding column.
-- Uses IVFFlat with 100 lists (adjust based on dataset size, ~300 rows).
-- Uncomment when embeddings are ready.
-- CREATE INDEX IF NOT EXISTS idx_product_documents_embedding
--   ON product_documents
--   USING ivfflat (embedding vector_cosine_ops)
--   WITH (lists = 100);

-- ============================================================================
-- TRIGGER: auto-update updated_at on row modification
-- ============================================================================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_product_intelligence_updated_at
  BEFORE UPDATE ON product_intelligence
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_product_documents_updated_at
  BEFORE UPDATE ON product_documents
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- NOTE: Migration Strategy
-- ============================================================================
-- When ready to apply:
-- 1. Enable pgvector extension in Supabase dashboard or via SQL above.
-- 2. Run this file in Supabase SQL editor or via migration tool.
-- 3. Create a data population script that:
--    a. Calls src/lib/enrichment-batch.ts for all products
--    b. Inserts into product_intelligence (one row per product)
--    c. Optionally chunks documents and inserts into product_documents
-- 4. Verify with: SELECT COUNT(*) FROM product_intelligence;
-- 5. For fallback products: insert with product_id = NULL, slug = product.slug
--    (they will be regenerated on schema upgrade if IDs change)
-- ============================================================================
