import type { Product } from "./types"

export const fallbackProducts: Product[] = [
  {
    id: "1",
    name: "iPhone 17 Pro Max",
    slug: "iphone-17-pro-max",
    brand: "Apple",
    category: "smartphones",
    description:
      "Apple's flagship smartphone featuring the A19 Pro chip, 48MP quad-camera system, and all-day battery life. Titanium design with edge-to-edge Super Retina XDR display.",
    image: "/images/placeholder.svg",
    price: 1299,
    currency: "USD",
    releaseDate: "2025-09-19",
    specs: {
      Chip: "A19 Pro",
      RAM: "12GB",
      Storage: "256GB / 512GB / 1TB",
      Display: "6.9″ Super Retina XDR OLED",
      Camera: "48MP Main + 48MP Ultra Wide + 12MP Telephoto 5x + LiDAR",
      Battery: "4685 mAh",
      OS: "iOS 19",
      Weight: "221g",
    },
    scores: {
      overall: 96,
      gaming: 98,
      camera: 97,
      battery: 92,
      display: 98,
      value: 85,
    },
    pros: [
      "Best-in-class performance",
      "Industry-leading camera system",
      "Premium titanium build",
      "Excellent display brightness",
    ],
    cons: [
      "Very expensive",
      "Charging could be faster",
      "No USB-C improvements",
    ],
  },
  {
    id: "2",
    name: "Samsung Galaxy S25 Ultra",
    slug: "samsung-galaxy-s25-ultra",
    brand: "Samsung",
    category: "smartphones",
    description:
      "Samsung's ultimate flagship with Galaxy AI, 200MP camera, S Pen support, and the Snapdragon 8 Gen 4 processor. Built for productivity and creativity.",
    image: "/images/placeholder.svg",
    price: 1199,
    currency: "USD",
    releaseDate: "2025-01-22",
    specs: {
      Chip: "Snapdragon 8 Gen 4",
      RAM: "12GB / 16GB",
      Storage: "256GB / 512GB / 1TB",
      Display: "6.9″ Dynamic AMOLED 2X 120Hz",
      Camera: "200MP Main + 12MP Ultra Wide + 10MP Telephoto 3x + 50MP Telephoto 5x",
      Battery: "5000 mAh",
      OS: "One UI 7 (Android 16)",
      Weight: "219g",
    },
    scores: {
      overall: 95,
      gaming: 97,
      camera: 96,
      battery: 94,
      display: 97,
      value: 88,
    },
    pros: [
      "Versatile camera with 200MP sensor",
      "S Pen integration",
      "Excellent display",
      "Fast charging",
    ],
    cons: [
      "One UI can feel bloated",
      "Bulky design",
      "AI features region-locked",
    ],
  },
  {
    id: "3",
    name: "Pixel 10 Pro",
    slug: "pixel-10-pro",
    brand: "Google",
    category: "smartphones",
    description:
      "Google's AI-first smartphone with Tensor G5, advanced computational photography, and exclusive Pixel AI features. The smartest Pixel yet.",
    image: "/images/placeholder.svg",
    price: 999,
    currency: "USD",
    releaseDate: "2025-10-15",
    specs: {
      Chip: "Google Tensor G5",
      RAM: "16GB",
      Storage: "128GB / 256GB / 512GB",
      Display: "6.7″ LTPO OLED 120Hz",
      Camera: "50MP Main + 48MP Ultra Wide + 48MP Telephoto 5x + Temperature",
      Battery: "5050 mAh",
      OS: "Android 16 (Pixel OS)",
      Weight: "199g",
    },
    scores: {
      overall: 91,
      gaming: 89,
      camera: 96,
      battery: 91,
      display: 93,
      value: 90,
    },
    pros: [
      "Best computational photography",
      "Clean, fast software",
      "Exclusive AI features",
      "Competitive price",
    ],
    cons: [
      "Tensor G5 not as fast as competitors",
      "Charging speed still slow",
      "Modem could be better",
    ],
  },
  {
    id: "4",
    name: "OnePlus 14",
    slug: "oneplus-14",
    brand: "OnePlus",
    category: "smartphones",
    description:
      "OnePlus flagship with Snapdragon 8 Gen 4, 100W charging, Hasselblad-tuned cameras, and a stunning 2K 120Hz AMOLED display.",
    image: "/images/placeholder.svg",
    price: 899,
    currency: "USD",
    releaseDate: "2026-01-15",
    specs: {
      Chip: "Snapdragon 8 Gen 4",
      RAM: "12GB / 16GB LPDDR5x",
      Storage: "256GB / 512GB UFS 4.0",
      Display: "6.82″ 2K AMOLED 120Hz",
      Camera: "50MP Main + 50MP Ultra Wide + 64MP Periscope 3x (Hasselblad)",
      Battery: "5400 mAh",
      Charging: "100W wired, 50W wireless",
      OS: "OxygenOS 15 (Android 16)",
      Weight: "210g",
    },
    scores: {
      overall: 92,
      gaming: 95,
      camera: 90,
      battery: 97,
      display: 94,
      value: 93,
    },
    pros: [
      "Blazing fast charging",
      "Excellent battery life",
      "Great value flagship",
      "Smooth OxygenOS experience",
    ],
    cons: [
      "Camera not quite best-in-class",
      "AI features behind competitors",
      "Software update policy improving but not Samsung/Apple level",
    ],
  },
  {
    id: "5",
    name: "Samsung Galaxy Z Fold 7",
    slug: "samsung-galaxy-z-fold-7",
    brand: "Samsung",
    category: "foldable-smartphones",
    description:
      "Samsung's most advanced foldable with a 7.6″ inner AMOLED display, Snapdragon 8 Gen 4, Galaxy AI on the big screen, and a refined hinge design. The ultimate productivity foldable.",
    image: "/images/placeholder.svg",
    price: 1899,
    currency: "USD",
    releaseDate: "2025-07-15",
    specs: {
      Chip: "Snapdragon 8 Gen 4",
      RAM: "12GB / 16GB",
      Storage: "256GB / 512GB / 1TB",
      InnerDisplay: "7.6″ Dynamic AMOLED 2X 120Hz",
      CoverDisplay: "6.3″ Dynamic AMOLED 2X 120Hz",
      Camera: "50MP Main + 12MP Ultra Wide + 10MP Telephoto 3x",
      Battery: "4400 mAh",
      OS: "One UI 7 (Android 16)",
      Weight: "253g",
    },
    scores: {
      overall: 90,
      gaming: 93,
      camera: 88,
      battery: 85,
      display: 96,
      value: 78,
    },
    pros: [
      "Best foldable display on the market",
      "Refined hinge with IP48 rating",
      "Galaxy AI features optimized for large screen",
      "S Pen support on main display",
    ],
    cons: [
      "Very expensive",
      "Camera not at S25 Ultra level",
      "Cover screen still narrow",
    ],
  },
  {
    id: "6",
    name: "Google Pixel Fold 3",
    slug: "google-pixel-fold-3",
    brand: "Google",
    category: "foldable-smartphones",
    description:
      "Google's third-gen foldable with Tensor G5, a 7.2″ smooth inner display, and Pixel's legendary computational photography in a slim foldable body.",
    image: "/images/placeholder.svg",
    price: 1799,
    currency: "USD",
    releaseDate: "2025-10-15",
    specs: {
      Chip: "Google Tensor G5",
      RAM: "16GB",
      Storage: "256GB / 512GB",
      InnerDisplay: "7.2″ LTPO OLED 120Hz",
      CoverDisplay: "6.0″ LTPO OLED 120Hz",
      Camera: "48MP Main + 12MP Ultra Wide + 10MP Telephoto 5x",
      Battery: "4650 mAh",
      OS: "Android 16 (Pixel OS)",
      Weight: "235g",
    },
    scores: {
      overall: 89,
      gaming: 88,
      camera: 94,
      battery: 86,
      display: 94,
      value: 80,
    },
    pros: [
      "Best camera on any foldable",
      "Slim and light design",
      "Clean Pixel software with exclusive AI",
      "Smooth 120Hz inner display",
    ],
    cons: [
      "Tensor G5 lags in raw performance",
      "Charging speed slow",
      "No stylus support",
    ],
  },
  {
    id: "7",
    name: "OnePlus Open 2",
    slug: "oneplus-open-2",
    brand: "OnePlus",
    category: "foldable-smartphones",
    description:
      "The second-gen OnePlus foldable with Snapdragon 8 Gen 4, a massive 8.0″ inner display, 100W fast charging, and Hasselblad-tuned cameras.",
    image: "/images/placeholder.svg",
    price: 1699,
    currency: "USD",
    releaseDate: "2026-02-15",
    specs: {
      Chip: "Snapdragon 8 Gen 4",
      RAM: "16GB LPDDR5x",
      Storage: "256GB / 512GB UFS 4.0",
      InnerDisplay: "8.0″ 2K AMOLED 120Hz",
      CoverDisplay: "6.5″ 2K AMOLED 120Hz",
      Camera: "50MP Main + 48MP Ultra Wide + 64MP Periscope 3x (Hasselblad)",
      Battery: "5000 mAh",
      Charging: "100W wired, 50W wireless",
      OS: "OxygenOS 15 (Android 16)",
      Weight: "239g",
    },
    scores: {
      overall: 91,
      gaming: 95,
      camera: 91,
      battery: 92,
      display: 95,
      value: 83,
    },
    pros: [
      "Blazing 100W fast charging",
      "Largest foldable inner display",
      "Best value among foldables",
      "Slim design for a large foldable",
    ],
    cons: [
      "Software update policy improving but limited",
      "Wireless charging slower than competitors",
      "Camera not quite Pixel level",
    ],
  },
]
